theme: jekyll-theme-slate
# https://pages-themes.github.io/slate/
# https://jekyll.github.io/minima/
# https://pages-themes.github.io/cayman/
title: Kiss-Skins
description: WordPressテーマCocoon用オリジナルスキン「Kiss」シリーズ配布ページ。
lang: ja
